f = function(x) if (x < 1000) exp(seq(log(x), log(1000), by=log(1.15))) else 1000
c = function(x) if (x < 2000) exp(seq(log(x), log(2000), by=log(1.45))) else 2000
t <-function(x){length(which(y$a_age < 5))} 

s <-function(x){length(which(y$a_age < 5))} 

y<-update(y, cost=0)


Clinton_Plan <-subset( 
		y , 
			(fownu18 == 0 & spmu_resources - spmu_actc < spmu_povthreshold) | 
			(fownu18 == 1 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 1*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 2 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 2*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 3 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 3*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 4 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 4*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 5 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 5*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 6 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 6*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 7 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 7*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 8 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 8*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 9 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 9*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 10 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 10*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 11 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 11*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 12 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 12*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 13 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 13*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 14 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 14*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 15 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 15*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 16 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 16*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 17 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 17*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 18 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 18*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 19 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 19*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) |
			(fownu18 >= 20 &  t(unique(h_seq)) == 0 & spmu_resources - spmu_actc + 20*f(ftotval) + 0*c(ftotval) < spmu_povthreshold) |
			(fownu18 == 1 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 1*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 2 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 2*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 3 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 3*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 4 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 4*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 5 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 5*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 6 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 6*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 7 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 7*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 8 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 8*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 9 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 9*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 10 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 10*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 11 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 11*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 12 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 12*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 13 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 13*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 14 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 14*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 15 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 15*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 16 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 16*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 17 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 17*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 18 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 18*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 19 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 19*f(ftotval) + 1*c(ftotval) < spmu_povthreshold) |
			(fownu18 == 20 &  t(unique(h_seq)) == 1 & spmu_resources - spmu_actc + 20*f(ftotval) + 1*c(ftotval) < spmu_povthreshold)	|		
			(fownu18 == 1 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 1*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 2 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 2*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 3 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 3*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 4 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 4*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 5 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 5*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 6 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 6*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 7 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 7*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 8 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 8*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 9 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 9*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 10 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 10*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 11 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 11*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 12 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 12*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 13 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 13*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 14 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 14*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 15 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 15*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 16 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 16*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 17 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 17*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 18 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 18*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 19 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 19*f(ftotval) + 2*c(ftotval) < spmu_povthreshold) |
			(fownu18 == 20 &  t(unique(h_seq)) == 2 & spmu_resources - spmu_actc + 20*f(ftotval) + 2*c(ftotval) < spmu_povthreshold)	|	
			(fownu18 == 1 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 1*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 2 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 2*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 3 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 3*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 4 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 4*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 5 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 5*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 6 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 6*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 7 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 7*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 8 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 8*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 9 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 9*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 10 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 10*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 11 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 11*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 12 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 12*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 13 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 13*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 14 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 14*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 15 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 15*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 16 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 16*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 17 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 17*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 18 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 18*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 19 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 19*f(ftotval) + 3*c(ftotval) < spmu_povthreshold) |
			(fownu18 == 20 &  t(unique(h_seq)) == 3 & spmu_resources - spmu_actc + 20*f(ftotval) + 3*c(ftotval) < spmu_povthreshold)	|	
			(fownu18 == 1 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 1*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 2 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 2*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 3 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 3*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 4 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 4*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 5 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 5*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 6 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 6*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 7 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 7*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 8 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 8*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 9 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 9*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 10 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 10*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 11 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 11*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 12 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 12*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 13 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 13*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 14 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 14*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 15 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 15*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 16 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 16*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 17 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 17*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 18 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 18*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 19 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 19*f(ftotval) + 4*c(ftotval) < spmu_povthreshold) |
			(fownu18 == 20 &  t(unique(h_seq)) == 4 & spmu_resources - spmu_actc + 20*f(ftotval) + 4*c(ftotval) < spmu_povthreshold)	|				
			(fownu18 == 1 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 1*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 2 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 2*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 3 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 3*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 4 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 4*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 5 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 5*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 6 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 6*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 7 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 7*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 8 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 8*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 9 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 9*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 10 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 10*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 11 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 11*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 12 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 12*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 13 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 13*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 14 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 14*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 15 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 15*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 16 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 16*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 17 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 17*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 18 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 18*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 19 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 19*f(ftotval) + 5*c(ftotval) < spmu_povthreshold) |
			(fownu18 == 20 &  t(unique(h_seq)) == 5 & spmu_resources - spmu_actc + 20*f(ftotval) + 5*c(ftotval) < spmu_povthreshold)	|	
			(fownu18 == 1 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 1*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 2 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 2*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 3 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 3*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 4 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 4*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 5 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 5*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 6 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 6*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 7 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 7*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 8 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 8*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 9 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 9*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 10 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 10*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 11 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 11*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 12 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 12*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 13 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 13*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 14 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 14*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 15 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 15*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 16 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 16*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 17 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 17*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 18 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 18*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) | 
			(fownu18 == 19 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 19*f(ftotval) + 6*c(ftotval) < spmu_povthreshold) |
			(fownu18 == 20 &  t(unique(h_seq)) == 6 & spmu_resources - spmu_actc + 20*f(ftotval) + 6*c(ftotval) < spmu_povthreshold))
